---
title: "Timothy Keyes's CV"
author: Timothy Keyes
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = here::here("data/"),  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```



```{r}
CV %>% 
  print_contact_info()
```


`r icons::fontawesome(name = "code")` Programming {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% 
  print_skill_bars(skill_type = "programming")
```

`r icons::fontawesome(name = "chart-pie")` Data analysis 
--------------------------------------------------------------------------------

```{r}
CV %>% 
  print_text_block(label = "data_analysis")
```


`r icons::fontawesome(name = "book")` Literate Coding {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% 
  print_skill_bars(skill_type = "literate")
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------


Resume generated in R with [**pagedown**](https://github.com/rstudio/pagedown)

Source code: [github.com/keyes-timothy/cv](https://github.com/keyes-timothy/cv)

Updated `r lubridate::stamp_date("March 1, 1999")(Sys.Date())`.

`r emo::ji("pride")`



Main
================================================================================

Timothy Keyes {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% 
  print_text_block(label = "intro")
```



Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

```{r}
CV %<>% 
  print_section(section_id = "education")
```


Select Employment {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% 
  print_section(section_id = "employment")
```




Select Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% 
  print_section(section_id = "academic_articles")
```




